---
# https://prometheus.io/docs/prometheus/latest/configuration/configuration/
# Global config
global:
  scrape_interval: 1m
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: caddy
    static_configs:
      - targets:
          - caddy:9000

  - job_name: blackbox_exporter
    metrics_path: /probe
    params:
      module:
        - http_2xx
    static_configs:
      - targets:
          - https://ps2alerts.com
          - https://wt.honu.pw
          - https://ps2.fisu.pw
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115

  - job_name: blackbox_exporter_ps2alerts
    metrics_path: /probe
    params:
      module:
        - http_ps2alerts_status
    static_configs:
      - targets:
          - https://api.ps2alerts.com/healthcheck
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115
